package personelCalisma.PersonelCalisma;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PersonelCalismaDesign extends VerticalLayout {
	protected TextField txtAdSoyad;
	protected ComboBox<personelCalisma.PersonelCalisma.Iller> cmbIller;
	protected ComboBox<personelCalisma.PersonelCalisma.Ilceler> cmbIlceler;
	protected RadioButtonGroup<java.lang.Integer> chksecim;
	protected DateField dtDogumTarihi;
	protected TextArea txtAciklama;
	protected Button btnKaydet;
	protected Grid<personelCalisma.PersonelCalisma.PersonelIsBasvurulari> grdPersonel;

	public PersonelCalismaDesign() {
		Design.read(this);
	}
}
